"""
ParagonEdu Web - PDF generation (reportlab, pure-python).
admission_form(school, student) -> BytesIO
report_card(result, school)     -> BytesIO   (Phase 4b)
broadsheet(class_name, data)    -> BytesIO   (Phase 4c)
"""
import io
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.units import mm
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (SimpleDocTemplate, Table, TableStyle, Paragraph,
                                Spacer, HRFlowable)
from reportlab.lib.enums import TA_CENTER

NAVY = colors.HexColor("#0E2A47")
GOLD = colors.HexColor("#C9A227")
LINE = colors.HexColor("#d4dae3")
MUTE = colors.HexColor("#5f7186")


def _styles():
    ss = getSampleStyleSheet()
    ss.add(ParagraphStyle("SchoolName", parent=ss["Title"], fontSize=18, textColor=NAVY,
                          alignment=TA_CENTER, spaceAfter=2))
    ss.add(ParagraphStyle("SubHead", parent=ss["Normal"], fontSize=9, textColor=MUTE,
                          alignment=TA_CENTER, spaceAfter=2))
    ss.add(ParagraphStyle("DocTitle", parent=ss["Normal"], fontSize=13, textColor=NAVY,
                          alignment=TA_CENTER, spaceBefore=8, spaceAfter=8, fontName="Helvetica-Bold"))
    ss.add(ParagraphStyle("Foot", parent=ss["Normal"], fontSize=8, textColor=MUTE, alignment=TA_CENTER))
    return ss


def _header(school, title, story, ss):
    name = (school.get("name") or "ParagonEdu School")
    story.append(Paragraph(name, ss["SchoolName"]))
    bits = []
    if school.get("session"): bits.append(str(school["session"]))
    if school.get("term"): bits.append(f"{school['term']} term")
    if bits:
        story.append(Paragraph(" &nbsp;|&nbsp; ".join(bits), ss["SubHead"]))
    story.append(Paragraph("Powered by Paragon Smart Learning Technologies", ss["SubHead"]))
    story.append(Spacer(1, 4))
    story.append(HRFlowable(width="100%", thickness=2, color=GOLD, spaceAfter=8))
    story.append(Paragraph(title, ss["DocTitle"]))


def admission_form(school, s):
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=18*mm, bottomMargin=16*mm,
                            leftMargin=18*mm, rightMargin=18*mm, title="Admission Form")
    ss = _styles()
    story = []
    _header(school, "STUDENT ADMISSION FORM", story, ss)

    def row(label, value):
        return [Paragraph(f"<b>{label}</b>", ss["Normal"]),
                Paragraph(str(value or "&nbsp;"), ss["Normal"])]

    data = [
        row("Full Name", s.get("full_name")),
        row("Admission No", s.get("admission_no")),
        row("Class", s.get("class_level")),
        row("Gender", s.get("gender")),
        row("Date of Birth", s.get("date_of_birth")),
        row("Parent / Guardian", s.get("parent_name")),
        row("Parent Phone", s.get("parent_phone")),
    ]
    t = Table(data, colWidths=[55*mm, 110*mm])
    t.setStyle(TableStyle([
        ("FONTSIZE",(0,0),(-1,-1),10.5),
        ("TOPPADDING",(0,0),(-1,-1),7), ("BOTTOMPADDING",(0,0),(-1,-1),7),
        ("LEFTPADDING",(0,0),(-1,-1),10),
        ("LINEBELOW",(0,0),(-1,-1),0.5,LINE),
        ("BACKGROUND",(0,0),(0,-1),colors.HexColor("#f0f3f8")),
        ("VALIGN",(0,0),(-1,-1),"MIDDLE"),
    ]))
    story.append(t)
    story.append(Spacer(1, 24))

    # signatures
    sig = [[Paragraph("_____________________________<br/><font size=8>Parent / Guardian Signature</font>", ss["Normal"]),
            Paragraph("_____________________________<br/><font size=8>Head Teacher Signature &amp; Date</font>", ss["Normal"])]]
    st = Table(sig, colWidths=[85*mm, 85*mm])
    st.setStyle(TableStyle([("TOPPADDING",(0,0),(-1,-1),18),("ALIGN",(0,0),(-1,-1),"CENTER")]))
    story.append(st)
    story.append(Spacer(1, 18))
    story.append(Paragraph("This form was generated by ParagonEdu Suite.", ss["Foot"]))

    doc.build(story)
    buf.seek(0)
    return buf


def report_card(r, school, logo_path=None):
    """r = output of webdb.compute_student_result(). logo_path optional (top-left)."""
    from reportlab.platypus import Image as RLImage
    import os
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=14*mm, bottomMargin=12*mm,
                            leftMargin=15*mm, rightMargin=15*mm, title="Report Card")
    ss = _styles()
    story = []

    # --- header with optional logo top-left ---
    name = (school.get("name") or "ParagonEdu School")
    bits = []
    if school.get("session"): bits.append(str(school["session"]))
    if school.get("term"): bits.append(f"{school['term']} term")
    sub = " &nbsp;|&nbsp; ".join(bits)
    head_text = Paragraph(name, ss["SchoolName"]) 
    sub_para = Paragraph(sub, ss["SubHead"]) if sub else Paragraph("", ss["SubHead"])
    powered = Paragraph("Powered by Paragon Smart Learning Technologies", ss["SubHead"])
    text_cell = [head_text, sub_para, powered]

    logo_flowable = ""
    if logo_path and os.path.exists(logo_path):
        try:
            logo_flowable = RLImage(logo_path, width=22*mm, height=22*mm, kind="proportional")
        except Exception:
            logo_flowable = ""
    htbl = Table([[logo_flowable, text_cell]], colWidths=[26*mm, 154*mm])
    htbl.setStyle(TableStyle([("VALIGN",(0,0),(-1,-1),"MIDDLE"),
                              ("ALIGN",(0,0),(0,0),"LEFT"),
                              ("LEFTPADDING",(0,0),(-1,-1),0),("RIGHTPADDING",(0,0),(-1,-1),0)]))
    story.append(htbl)
    story.append(Spacer(1, 4))
    story.append(HRFlowable(width="100%", thickness=2, color=GOLD, spaceAfter=8))
    story.append(Paragraph("STUDENT REPORT CARD", ss["DocTitle"]))

    st = r["student"]
    info_tbl = [[
        Paragraph(f"<b>Name:</b> {st.get('full_name','')}", ss["Normal"]),
        Paragraph(f"<b>Admission No:</b> {st.get('admission_no','') or '-'}", ss["Normal"]),
        Paragraph(f"<b>Class:</b> {st.get('class_level','') or '-'}", ss["Normal"]),
    ]]
    it = Table(info_tbl, colWidths=[72*mm, 56*mm, 52*mm])
    it.setStyle(TableStyle([("FONTSIZE",(0,0),(-1,-1),9.5),("BOTTOMPADDING",(0,0),(-1,-1),6)]))
    story.append(it)
    story.append(Spacer(1, 4))

    # --- cognitive (academic) table ---
    m = r["maxima"]
    head = ["Subject", f"CA1\n({m['ca1']})", f"CA2\n({m['ca2']})", f"Exam\n({m['exam']})",
            f"Total\n({m['total']})", "Grade", "Remark"]
    rows = [head]
    for row in r["rows"]:
        rows.append([row["subject"], str(row["ca1"]), str(row["ca2"]), str(row["exam"]),
                     str(row["total"]), row["grade"], row["remark"]])
    t = Table(rows, colWidths=[48*mm, 16*mm, 16*mm, 18*mm, 20*mm, 16*mm, 32*mm], repeatRows=1)
    t.setStyle(TableStyle([
        ("BACKGROUND",(0,0),(-1,0),NAVY), ("TEXTCOLOR",(0,0),(-1,0),colors.white),
        ("FONTNAME",(0,0),(-1,0),"Helvetica-Bold"), ("FONTSIZE",(0,0),(-1,0),8.5),
        ("FONTSIZE",(0,1),(-1,-1),9), ("ALIGN",(1,0),(-1,-1),"CENTER"),
        ("VALIGN",(0,0),(-1,-1),"MIDDLE"),
        ("ROWBACKGROUNDS",(0,1),(-1,-1),[colors.white, colors.HexColor("#f5f7fa")]),
        ("GRID",(0,0),(-1,-1),0.4,LINE), ("TOPPADDING",(0,0),(-1,-1),4),("BOTTOMPADDING",(0,0),(-1,-1),4),
    ]))
    story.append(Paragraph("<b>Cognitive (Academic)</b>", ss["Normal"]))
    story.append(Spacer(1, 3))
    story.append(t)
    story.append(Spacer(1, 6))

    summ = [[
        Paragraph(f"<b>Subjects:</b> {r['subjects_counted']}", ss["Normal"]),
        Paragraph(f"<b>Total:</b> {r['grand_total']}", ss["Normal"]),
        Paragraph(f"<b>Average:</b> {r['average']}", ss["Normal"]),
        Paragraph(f"<b>Overall Grade:</b> {r['overall_grade']}", ss["Normal"]),
    ]]
    smt = Table(summ, colWidths=[42*mm, 42*mm, 46*mm, 50*mm])
    smt.setStyle(TableStyle([
        ("FONTSIZE",(0,0),(-1,-1),10),("BACKGROUND",(0,0),(-1,-1),colors.HexColor("#f0f3f8")),
        ("BOX",(0,0),(-1,-1),0.5,LINE),("TOPPADDING",(0,0),(-1,-1),7),("BOTTOMPADDING",(0,0),(-1,-1),7),
        ("LEFTPADDING",(0,0),(-1,-1),10),
    ]))
    story.append(smt)
    story.append(Spacer(1, 8))

    # --- affective + psychomotor side by side ---
    def domain_table(title, items):
        data = [[title, "Rating"]]
        for trait, rating, label in items:
            data.append([trait, (f"{rating} - {label}" if rating else "-")])
        dt = Table(data, colWidths=[52*mm, 36*mm], repeatRows=1)
        dt.setStyle(TableStyle([
            ("BACKGROUND",(0,0),(-1,0),colors.HexColor("#15395f")),("TEXTCOLOR",(0,0),(-1,0),colors.white),
            ("FONTNAME",(0,0),(-1,0),"Helvetica-Bold"),("FONTSIZE",(0,0),(-1,-1),8.5),
            ("ALIGN",(1,0),(1,-1),"CENTER"),("VALIGN",(0,0),(-1,-1),"MIDDLE"),
            ("GRID",(0,0),(-1,-1),0.4,LINE),("TOPPADDING",(0,0),(-1,-1),3.5),("BOTTOMPADDING",(0,0),(-1,-1),3.5),
            ("ROWBACKGROUNDS",(0,1),(-1,-1),[colors.white, colors.HexColor("#f5f7fa")]),
        ]))
        return dt

    aff = domain_table("Affective Domain", r.get("affective", []))
    psy = domain_table("Psychomotor Domain", r.get("psychomotor", []))
    side = Table([[aff, psy]], colWidths=[90*mm, 90*mm])
    side.setStyle(TableStyle([("VALIGN",(0,0),(-1,-1),"TOP"),
                              ("LEFTPADDING",(0,0),(-1,-1),0),("RIGHTPADDING",(0,0),(0,0),6)]))
    story.append(side)
    story.append(Spacer(1, 8))

    # --- comments ---
    tc = r.get("teacher_comment") or "________________________________________________"
    hc = r.get("head_comment") or "________________________________________________"
    cmt = Table([
        [Paragraph(f"<b>Class Teacher's Comment:</b> {tc}", ss["Normal"])],
        [Paragraph(f"<b>Head Teacher's Comment:</b> {hc}", ss["Normal"])],
    ], colWidths=[180*mm])
    cmt.setStyle(TableStyle([("FONTSIZE",(0,0),(-1,-1),9.5),("TOPPADDING",(0,0),(-1,-1),7),
                             ("BOTTOMPADDING",(0,0),(-1,-1),7),("LEFTPADDING",(0,0),(-1,-1),10),
                             ("BOX",(0,0),(-1,-1),0.5,LINE),("LINEBELOW",(0,0),(0,0),0.4,LINE),
                             ("BACKGROUND",(0,0),(-1,-1),colors.HexColor("#fbfcfe"))]))
    story.append(cmt)
    story.append(Spacer(1, 6))
    story.append(Paragraph("Generated by ParagonEdu Suite \u2014 Paragon Smart Learning Technologies", ss["Foot"]))

    doc.build(story)
    buf.seek(0)
    return buf


def broadsheet(class_name, subjects, rows, school, maxima):
    """
    subjects: list of subject names (columns)
    rows: list of dicts -> {"name","admission_no","scores":{subj:total}, "total","average","grade","position"}
    """
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=landscape(A4), topMargin=14*mm, bottomMargin=12*mm,
                            leftMargin=12*mm, rightMargin=12*mm, title="Broadsheet")
    ss = _styles()
    story = []
    _header(school, f"CLASS BROADSHEET \u2014 {class_name}", story, ss)

    head = ["#", "Student"] + [s[:10] for s in subjects] + ["Total", "Avg", "Grade", "Pos"]
    data = [head]
    for i, r in enumerate(rows, 1):
        line = [str(i), r["name"]]
        for subj in subjects:
            v = r["scores"].get(subj, "")
            line.append(str(v) if v != "" else "-")
        line += [str(r["total"]), str(r["average"]), r["grade"], str(r["position"])]
        data.append(line)

    nsub = len(subjects)
    subj_w = max(14, min(22, int(150 / max(nsub,1))))
    col_w = [9*mm, 46*mm] + [subj_w*mm]*nsub + [16*mm, 14*mm, 14*mm, 12*mm]
    t = Table(data, colWidths=col_w, repeatRows=1)
    t.setStyle(TableStyle([
        ("BACKGROUND",(0,0),(-1,0),NAVY),("TEXTCOLOR",(0,0),(-1,0),colors.white),
        ("FONTNAME",(0,0),(-1,0),"Helvetica-Bold"),("FONTSIZE",(0,0),(-1,0),7.5),
        ("FONTSIZE",(0,1),(-1,-1),8),("ALIGN",(0,0),(-1,-1),"CENTER"),
        ("ALIGN",(1,1),(1,-1),"LEFT"),("VALIGN",(0,0),(-1,-1),"MIDDLE"),
        ("ROWBACKGROUNDS",(0,1),(-1,-1),[colors.white, colors.HexColor("#f5f7fa")]),
        ("GRID",(0,0),(-1,-1),0.4,LINE),("TOPPADDING",(0,0),(-1,-1),4),("BOTTOMPADDING",(0,0),(-1,-1),4),
    ]))
    story.append(t)
    story.append(Spacer(1, 10))
    story.append(Paragraph(f"Class size: {len(rows)} &nbsp;|&nbsp; Max total per subject: {maxima['total']}", ss["Foot"]))
    story.append(Paragraph("Generated by ParagonEdu Suite", ss["Foot"]))
    doc.build(story)
    buf.seek(0)
    return buf


def accounts_report(s, school, logo_path=None):
    """Financial summary report: income, expenses (by category), balance."""
    from reportlab.platypus import Image as RLImage
    import os
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=16*mm, bottomMargin=14*mm,
                            leftMargin=16*mm, rightMargin=16*mm, title="Financial Report")
    ss = _styles()
    story = []
    # header with logo
    name = school.get("name") or "ParagonEdu School"
    logo_flow = ""
    if logo_path and os.path.exists(logo_path):
        try: logo_flow = RLImage(logo_path, width=20*mm, height=20*mm, kind="proportional")
        except Exception: logo_flow = ""
    text_cell = [Paragraph(name, ss["SchoolName"]),
                 Paragraph("Powered by Paragon Smart Learning Technologies Limited", ss["SubHead"])]
    htbl = Table([[logo_flow, text_cell]], colWidths=[24*mm, 156*mm])
    htbl.setStyle(TableStyle([("VALIGN",(0,0),(-1,-1),"MIDDLE"),("LEFTPADDING",(0,0),(-1,-1),0)]))
    story.append(htbl)
    story.append(HRFlowable(width="100%", thickness=2, color=GOLD, spaceAfter=8, spaceBefore=4))
    title = f"FINANCIAL REPORT"
    if s.get("session") or s.get("term"):
        title += f" — {s.get('session','')} {s.get('term','')} term".rstrip()
    story.append(Paragraph(title, ss["DocTitle"]))

    # summary box
    summ = [
        ["Fees collected (income)", naira_pdf(s["income"])],
        ["Total expenses", naira_pdf(s["expense"])],
        ["NET BALANCE", naira_pdf(s["balance"])],
    ]
    t = Table(summ, colWidths=[110*mm, 60*mm])
    t.setStyle(TableStyle([
        ("FONTSIZE",(0,0),(-1,-1),11),("TOPPADDING",(0,0),(-1,-1),9),("BOTTOMPADDING",(0,0),(-1,-1),9),
        ("LEFTPADDING",(0,0),(-1,-1),12),("ALIGN",(1,0),(1,-1),"RIGHT"),
        ("LINEBELOW",(0,0),(-1,-2),0.4,LINE),
        ("BACKGROUND",(0,2),(-1,2),colors.HexColor("#0E2A47")),("TEXTCOLOR",(0,2),(-1,2),colors.white),
        ("FONTNAME",(0,2),(-1,2),"Helvetica-Bold"),
        ("BOX",(0,0),(-1,-1),0.5,LINE),
    ]))
    story.append(t)
    story.append(Spacer(1, 14))

    # expenses by category
    if s.get("by_category"):
        story.append(Paragraph("<b>Expenses by category</b>", ss["Normal"]))
        story.append(Spacer(1, 4))
        rows = [["Category", "Amount"]]
        for c in s["by_category"]:
            rows.append([c["category"] or "—", naira_pdf(c["total"])])
        ct = Table(rows, colWidths=[110*mm, 60*mm], repeatRows=1)
        ct.setStyle(TableStyle([
            ("BACKGROUND",(0,0),(-1,0),colors.HexColor("#15395f")),("TEXTCOLOR",(0,0),(-1,0),colors.white),
            ("FONTNAME",(0,0),(-1,0),"Helvetica-Bold"),("FONTSIZE",(0,0),(-1,-1),10),
            ("ALIGN",(1,0),(1,-1),"RIGHT"),("GRID",(0,0),(-1,-1),0.4,LINE),
            ("ROWBACKGROUNDS",(0,1),(-1,-1),[colors.white, colors.HexColor("#f5f7fa")]),
            ("TOPPADDING",(0,0),(-1,-1),6),("BOTTOMPADDING",(0,0),(-1,-1),6),("LEFTPADDING",(0,0),(-1,-1),12),
        ]))
        story.append(ct)
        story.append(Spacer(1, 14))

    # context
    story.append(Paragraph(f"<b>Expected fees this term:</b> {naira_pdf(s.get('expected',0))} &nbsp;&nbsp; "
                           f"<b>Still outstanding:</b> {naira_pdf(s.get('outstanding',0))}", ss["Normal"]))
    story.append(Spacer(1, 20))
    story.append(Paragraph("Generated by ParagonEdu Suite", ss["Foot"]))
    doc.build(story)
    buf.seek(0)
    return buf


def naira_pdf(n):
    try:
        return "NGN {:,.0f}".format(float(n or 0))
    except Exception:
        return "NGN 0"
